web/rest_api/forms/address.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired







class AddressCreateForm (FlaskForm):

    line1 = StringField("Line1", validators=[DataRequired()], description="Line 1")
    line2 = StringField("Line2", description="Line 2")
    city = StringField("City", validators=[DataRequired()], description="City")
    state= StringField("State", validators=[DataRequired()], description="State")
    zip = StringField("Zip Code", validators=[DataRequired()], description="Zip")


    submit = SubmitField("Save Address")

web/rest_api/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, PasswordField
from wtforms.validators import DataRequired
from rest_api.models.user import UserModel
from rest_api.models.staff import StaffModel
from werkzeug.security import check_password_hash


class AuthLogin(FlaskForm):
    username = StringField("username", validators=[DataRequired()], description="Username")
    password = PasswordField("password", validators=[DataRequired()], description="Password")
    submit = SubmitField("Login")

    def validate_username(self, username):
        if (not UserModel.find_by_name(username.data)) and (not StaffModel.find_by_name(username.data)):
            raise ValidationError("username doesn't exist.")
    

web/rest_api/forms/company.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email

# from flask_login import current_user
from rest_api.models.company import CompanyModel







class RegistrationForm (FlaskForm):
    company_name = StringField("Company Name", validators=[DataRequired()], description="Company Name")
    email = StringField("Email", validators=[DataRequired(), Email()], description="Email")
    phone = StringField("Phone", validators=[DataRequired()], description="Phone")

    line1 = StringField("Line1", validators=[DataRequired()], description="Line 1")
    line2 = StringField("Line2", description="Line 2")
    city = StringField("City", validators=[DataRequired()], description="City")
    state= StringField("State", validators=[DataRequired()], description="State")
    zip = StringField("Zip Code", validators=[DataRequired()], description="Zip")
    submit = SubmitField("Register!")

    def validate_company_name(self, company_name):

        if CompanyModel.find_by_name(company_name.data):
            raise ValidationError("Company name already exists.")


    def validate_email(self, email):
        if CompanyModel.find_by_email(email.data):
            raise ValidationError("Email already exists.")


class UpdateForm (FlaskForm):
    company_name = StringField("Company Name", validators=[DataRequired()], description="Company Name")
    email = StringField("Email", validators=[DataRequired(), Email()], description="Email")
    phone = StringField("Phone", validators=[DataRequired()], description="Phone")


    submit = SubmitField("Update")

web/rest_api/views/address.py
from flask import Blueprint, render_template, redirect, url_for
from rest_api.forms.address import AddressCreateForm
from rest_api.models.address import AddressModel
address_bp = Blueprint("address", __name__)




@address_bp.route("/create/<int:company_id><int:user_id>", methods=["GET", "POST"])
def address_create(company_id, user_id):

    form = AddressCreateForm()

    if form.validate_on_submit():
        address = AddressModel(
            line1=form.line1.data,
            line2=form.line2.data,
            city=form.city.data,
            state=form.state.data,
            zip=form.zip.data,
            company_id=company_id,
            user_id =user_id
        )
        address.save_to_db()

        return redirect(url_for("company.company_info"))

    return render_template("address_create.html", form=form)


@address_bp.route("/update/<int:address_id>", methods=["GET","POST"])
def address_update(address_id):
    form = AddressCreateForm()

    address = AddressModel.find_by_id(address_id)

    if form.validate_on_submit():
        address.line1 = form.line1.data
        address.line2 = form.line2.data
        address.city =  form.city.data
        address.state= form.state.data
        address.zip = form.zip.data

        address.save_to_db()

        return redirect(url_for("company.company_info"))

    form.line1.data = address.line1
    form.line2.data = address.line2
    form.city.data = address.city
    form.state.data = address.state
    form.zip.data = address.zip

    return render_template("address_create.html", form = form)



# @address_bp.route("/info")
# def address_info():
#     pass

@address_bp.route("/delete/<int:address_id>", methods=["GET","POST"])
def address_delete(address_id):
    
    address = AddressModel.find_by_id(address_id)
    
    if address:
        address.delete_from_db()
    
    return redirect(url_for("company.company_info"))

web/rest_api/views/home.py
from flask import Blueprint, render_template, redirect, url_for,request
from rest_api.forms.order import OrderCheckStatusByNumberForm, OrderCheckStatusByQRCodeForm
from rest_api.models.order import OrderModel
from rest_api.controls.urcode_generator import decode_qrcode
home_bp = Blueprint("web", __name__)

@home_bp.route("/", methods=["GET","POST"])
def index():
    search_method = request.args.get("search_method", "by_order_number", type=str)

    if search_method == "by_order_number":
        form = OrderCheckStatusByNumberForm()
        if form.validate_on_submit():
            order = OrderModel.find_by_ur_code(form.order_number.data)
            if order:
                return redirect(url_for("order.order_info", order_id=order.id)) 

    else:
        form = OrderCheckStatusByQRCodeForm()
        if form.validate_on_submit():
            decoded_data = decode_qrcode(form.qrcode_img.data)
            order = OrderModel.find_by_ur_code(decoded_data)
            if order:
                return redirect(url_for("order.order_info", order_id=order.id))

    return render_template("home.html", form=form, search_method=search_method)

web/rest_api/views/order.py
from flask import Blueprint, render_template, redirect, url_for, request
from rest_api.forms.order import OrderCreateForm, OrderUpdateForm, OrderCheckStatusByNumberForm, OrderCheckStatusByQRCodeForm
from rest_api.models.order import OrderModel
from rest_api.models.tracking import TrackingModel
from rest_api.models.company import CompanyModel
from flask_login import login_required, current_user
from rest_api.models.staff import StaffModel
from rest_api.controls.auth import (
    is_admin,
    is_company_admin,
    is_staff,
    is_user,
    render_error_page_unauthorized_access)
from rest_api.controls.urcode_generator import (
    generate_qrcode,
    generate_order_number,
    generate_and_validate_order_number,
    decode_qrcode)

order_bp = Blueprint("order", __name__)


@order_bp.route("/create", methods=["GET","POST"])
@login_required
def order_create():

    if is_user(current_user):
        return render_error_page_unauthorized_access()

    form = OrderCreateForm()

    if form.validate_on_submit():

        order = OrderModel(
            ur_code=form.ur_code.data,
            name=form.name.data,
            staff_id=form.staff_id.data
        )
        order.save_to_db()

        return redirect(url_for("order.order_info",order_id=order.id))
    
    order_number = generate_and_validate_order_number(generate_order_number)
    generate_qrcode(order_number)
    form.ur_code.data = order_number
    form.staff_id.data=current_user.id
    extension=".jpg"
    return render_template("order_create.html", form=form, extension=extension)


@order_bp.route("/update/<int:order_id>", methods=["GET","POST"])
def order_update(order_id):

    order = OrderModel.find_by_id(order_id)

    form = OrderUpdateForm()

    if form.validate_on_submit():
        order.name = form.name.data
        order.staff_id = form.staff_id.data
        order.save_to_db()
        return redirect(url_for("order.order_info", order_id=order.id))

    form.name.data = order.name
    form.staff_id.data = order.staff_id
    return render_template("order_update.html", form=form)


@order_bp.route("/info/<int:order_id>", methods=["GET","POST"])
def order_info(order_id):

    order = OrderModel.find_by_id(order_id)

    page = request.args.get("page", 1, type=int)

    posts = TrackingModel.find_by_order_id(order_id).paginate(page=page, per_page=10)

    return render_template("order_info.html", order=order, posts=posts)


@order_bp.route("/delete/<int:order_id>")
def order_delete(order_id):
    order = OrderModel.find_by_id(order_id)

    if order:
        order.delete_from_db()

        return redirect(url_for("order.order_list"))


@order_bp.route("/list")
@login_required
def order_list():
    
    page = request.args.get("page", 1, type=int)

    if is_admin(current_user):
        orders = OrderModel.find_all().paginate(page=page, per_page=5)

    elif is_company_admin(current_user):
        orders=OrderModel.find_by_company(current_user.company).paginate(page=page, per_page=5)
        # orders=OrderModel.find_by_company_id(current_user.company_id).paginate(page=page, per_page=5)

    elif is_staff(current_user):
        orders = OrderModel.find_by_staff_id(current_user.id).paginate(page=page, per_page=5)
    elif is_user(current_user):
        orders = OrderModel.find_by_user_id(current_user.id).paginate(page=page, per_page=5)

    return render_template("order_list.html", orders=orders)



@order_bp.route("check_status", methods=["GET","POST"])
def order_check_status():
    form = OrderCheckStatusByNumberForm()

    if form.validate_on_submit():
        order = OrderModel.find_by_ur_code(form.order_number.data)
        if order:
            return redirect(url_for("order.order_info", order_id=order.id))

    return render_template("order_check_status.html", form=form)

@order_bp.route("check_status_qrcode", methods=["GET","POST"])
def order_check_status_qrcode():
    form = OrderCheckStatusByQRCodeForm()

    if form.validate_on_submit():

        decoded_data = decode_qrcode(form.qrcode_img.data)

        order = OrderModel.find_by_ur_code(decoded_data)
        if order:
            return redirect(url_for("order.order_info", order_id=order.id))

    return render_template("order_check_status.html", form=form)

web/rest_api/views/staff.py
from flask import Blueprint, render_template, redirect, url_for, request
from rest_api.forms.staff import StaffCreateForm, StaffUpdateForm
from rest_api.models.staff import StaffModel
from werkzeug.security import generate_password_hash
from flask_login import login_required, current_user
from rest_api.controls.auth import (
    is_admin_or_company_admin_of_the_same_company,
    is_admin,
    is_company_admin,
    is_user,
    is_staff,
    render_error_page_unauthorized_access)

staff_bp = Blueprint("staff", __name__)

@staff_bp.route("/register", methods=["GET","POST"])
@login_required
def staff_register():
    
    if is_user(current_user) or is_staff(current_user):
        return render_error_page_unauthorized_access()

    form = StaffCreateForm()

    if form.validate_on_submit():
        if is_company_admin(current_user) and current_user.company_id !=form.company_id.data:
            return render_error_page_unauthorized_access()
        try:
            staff = StaffModel(
                form.username.data,
                form.role.data,
                generate_password_hash(form.password.data),
                form.company_id.data)

            staff.save_to_db()
        except:
            return {"message":"something went wrong"}
        return redirect(url_for("staff.staff_info"))

    return render_template("staff_register.html", form = form)


# @staff_bp.route("/login")
# def staff_login():
#     return render_template("staff_login.html")


@staff_bp.route("/info")
@login_required
def staff_info():
    
    page = request.args.get("page", 1, type=int)

    if is_user(current_user):
        return render_error_page_unauthorized_access()
    
    if is_admin(current_user):
        staffs= StaffModel.find_all()
    elif is_company_admin(current_user) or is_staff(current_user):
        staffs= StaffModel.find_by_company_id(current_user.company_id)

    staffs = staffs.paginate(page=page, per_page=5)

    return render_template("staff_info.html", staffs=staffs)


@staff_bp.route("/update/<int:staff_id>", methods=["GET","POST"])
def staff_update(staff_id):

    staff = StaffModel.find_by_id(staff_id)

    form = StaffUpdateForm()

    if form.validate_on_submit():
        staff.role =  form.role.data
        staff.password_hash = generate_password_hash(form.password.data)
        staff.company_id = form.company_id.data
        staff.save_to_db()
        return redirect(url_for("staff.staff_info"))

    form.role.data = staff.role
    form.company_id.data = staff.company_id

    return render_template("staff_update.html", form=form, staff=staff)

@staff_bp.route("/close_account/<int:staff_id>", methods=["GET","POST"])
def staff_close_account(staff_id):

    staff = StaffModel.find_by_id(staff_id)

    staff.delete_from_db()

    return redirect(url_for("staff.staff_info"))

@staff_bp.route("/workspace")
def staff_workspace():

    return render_template("staff_workspace.html")

web/rest_api/views/user.py
from flask import Blueprint, render_template, redirect, url_for, request
from rest_api.forms.user import UserCreateForm, UserUpdateForm
from rest_api.models.user import UserModel
from rest_api.models.user import OrderModel
from werkzeug.security import generate_password_hash
user_bp = Blueprint("user", __name__)
from flask_login import login_required, current_user
from rest_api.controls.auth import(
    is_admin,
    is_company_admin,
    is_staff,
    is_user,
    render_error_page_unauthorized_access
)

@user_bp.route("/register", methods=["GET", "POST"])
def user_register():

    form = UserCreateForm()

    if form.validate_on_submit():
        user = UserModel(
            hashed_password = generate_password_hash(form.password.data),
            name = form.username.data,
            email = form.email.data,
            phone = form.phone.data
        )
        user.save_to_db()
        return redirect(url_for("web.index"))

    return render_template("user_register.html", form=form)


# @user_bp.route("/login")
# def user_login():
#     return render_template("user_login.html")


@user_bp.route("/account")
@login_required
def user_account():

    if is_user(current_user):
        user_id = current_user.id

    else:
        user_id = request.args.get("user_id", type=int)
    
    user = UserModel.find_by_id(user_id)
    return render_template("user_account.html", user=user)


@user_bp.route("/user_list")
@login_required
def user_list ():

    # no access to users(customers)
    if is_user(current_user):
        return render_error_page_unauthorized_access()

    # admin sees all users
    if is_admin(current_user):
        users = UserModel.find_all()
    # company_admin and staff sees all users of their company
    if is_company_admin or is_staff:
        pass

    page = request.args.get("page", 1, type=int)
    users = users.paginate(page=page, per_page=5)

    return render_template("user_list.html", users=users)



# update and close account can all be done in account page using diff forms. 

@user_bp.route("/update", methods=["GET","POST"])
@login_required
def user_update():
    if is_staff(current_user) or is_company_admin(current_user):
        return render_error_page_unauthorized_access()
    if is_user(current_user):
        user_id = current_user.id
    elif is_admin(current_user):
        user_id = request.args.get("user_id")

    user = UserModel.find_by_id(user_id)

    form = UserUpdateForm()

    if form.validate_on_submit():
        user.email=form.email.data
        user.phone = form.phone.data
        user.password_hash = generate_password_hash(form.password.data)
        user.save_to_db()

        return render_template("user_account.html", user=user)

    form.email.data = user.email
    form.phone.data = user.phone

    return render_template("user_update.html", form=form)


@user_bp.route("/close_account")
@login_required
def user_close_account():

    user_id = request.args.get("user_id")
    user= UserModel.find_by_id(user_id)
    if user:
        user.delete_from_db()

    return redirect(url_for("web.index"))


@user_bp.route("/add_order")
@login_required
def user_add_order():
    order_id = request.args.get("order_id")
    order = OrderModel.find_by_id(order_id)
    if order:
        order.user_id = current_user.id
    order.save_to_db()

    return redirect(url_for("order.order_list"))

web/rest_api/templates/admin_control_panel.html
{% extends "base.html" %}
{% block content %}

<div class="container text-center">

    <h5><a href="{{url_for("company.company_create")}}">Add new company</a></h5>
    <h5><a href="{{url_for("company.company_info")}}">View existing companies</a></h5>
    <h5><a href="{{url_for("staff.staff_register")}}">Register new staff</a></h5>
    <h5><a href="{{url_for("staff.staff_info")}}">View existing staffs</a></h5>
    <h5><a href="{{url_for("order.order_create")}}">Create New Order</a></h5>
    <h5><a href="{{url_for("order.order_list")}}">View existing Orders</a></h5>
    <h5><a href="{{url_for("user.user_register")}}">Register new user</a></h5>
    <h5><a href="{{url_for("user.user_list")}}">View existing users</a></h5>
</div>



{% endblock %}

web/rest_api/templates/company_info.html
{% extends "base.html" %}
{% block content %}



<div class="container">

    <p>Our Partners</p> <br>

    {% for company in companies.items %}

        <h3>{{company.name}} </h3>
        <p>contacts:</p>
        <p>Tel: {{company.phone}}</p>
        <p>Email: {{company.email}}</p>
        {% if current_user.is_authenticated and current_user.role and current_user.role == "admin" %}
        <a href="{{ url_for("company.company_close_account", company_id=company.id) }}">Delete</a> | 
        <a href="{{ url_for("company.company_update", company_id=company.id) }}">Edit</a> | 
        <a href="{{ url_for("address.address_create", company_id=company.id, user_id=1) }}">Add Location</a>
        {% endif %}
        <br>
        <br>
        <h6>locations:</h6>
        {% for address in company.get_active_addresses() %}
            <p>
                {{address.json()}}
            </p>
            {% if current_user.is_authenticated and current_user.role and current_user.role == "admin" %}
            <a href="{{ url_for("address.address_update", address_id=address.id) }}">Edit</a> | 
            <a href="{{ url_for("address.address_delete", address_id=address.id) }}">Delete</a>
            {% endif %}
            <br>
            <br>


        {% endfor %}

    {% endfor %}
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% for page_num in companies.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
         {% if companies.page == page_num %}
         <li class="page-item disabled">
           <a class="page-link" href="{{ url_for('company.company_info', page=page_num) }}">{{ page_num }}</a></li>
         </li>
         {% else %}
           <li class="page-item"><a class="page-link" href="{{ url_for('company.company_info', page=page_num) }}">{{ page_num }}</a></li>
         {% endif %}
     {% endfor %}
   </nav>


{% endblock %}

web/rest_api/templates/error.html
{% extends "base.html" %}
{% block content %}


<div>

    <h4>
        {{message}}
    </h4>
</div>

{% endblock %}

web/rest_api/templates/home.html
{% extends "base.html" %}


{% block dashboard %}
{% endblock %}

{% block content %}



<div class="text-center mt-5">
    <br>
    <br>
    <br>
    <p><a href="{{url_for("user.user_register")}}">Register</a> for free account</p> 
    <p>Login to access and manage all your past orders!</p>
    <br>
    {% from "_formhelpers.html" import render_field %}
    <form class="form-inline mt-2 mt-md-0" action="" method="POST" enctype="multipart/form-data">
        <div class="mx-auto">
        {% for field in form %}
            {{ render_field(field)}}
        {% endfor %}
        </div>
    </form>
    <br>
    
    {% if search_method=="by_order_number" %}
    <a href="{{url_for("web.index", search_method="by_qrcode")}}">Search by QR-code image</a>
    {% else %}   
    <a href="{{url_for("web.index", search_method="by_order_number")}}">Search by Order Number</a>
    {% endif %}
</div>


{% endblock %}

web/rest_api/templates/login.html
{% extends "base.html" %}
{% block content %}



<div class="container text-center mt-5" style="width:400px">
    <p>User Login</p>
        {% from "_formhelpers.html" import render_field %}
    
    
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.password)}}
            {{ form.submit()}}
        </form>
        <br>
        <p>no account yet? <a href="{{url_for("user.user_register")}}">Register a free account</a></p>
    </div>

{% endblock %}

web/rest_api/templates/order_check_status.html
{% extends "base.html" %}
{% block content %}



{% from "_formhelpers.html" import render_field %}

<hr>
<div class="jumbotron text-center">

    

    <form class="form-inline mt-2 mt-md-0" action="" method="POST" enctype="multipart/form-data">
        <div class="mx-auto">
        {% for field in form %}
            {{ render_field(field)}}
        {% endfor %}
        </div>
    </form>
    <br>
    <br>
    <a href="{{url_for("order.order_check_status_qrcode")}}">Check by QR Code</a>   |   
    <a href="{{url_for("order.order_check_status")}}">Check by Order Number</a>

</div>

{% endblock %}

web/rest_api/templates/order_create.html
{% extends "base.html" %}
{% block content %}



<div class="container text-center mt-5" style="width:400px">
    <p>Create a New Order</p>
    {% from "_formhelpers.html" import render_field %}
    <img src="{{url_for("static", filename="order_qr/"+form.ur_code.data + extension)}}" alt="">
    <br>
    <form method="POST">
        {{form.hidden_tag()}}
        {{ render_field(form.ur_code)}} 
        {{ render_field(form.name)}}
        {{ render_field(form.staff_id)}}
        {{form.submit()}}
    </form>
</div>


{% endblock %}

web/rest_api/templates/order_list.html
{% extends "base.html" %}
{% block content %}


<div class="jumbotron text-center">

    {% for order in orders.items %}

        <h3><a href="{{ url_for("order.order_info", order_id=order.id) }}">order id: {{order.id}}</a> </h3>
        <p>order date: {{order.date.strftime("%B %d, %Y")}}</p>
        <p>staff: {{order.staff.name}}</p>
        <p>company:{{ order.company.name }}</p>
    
    {% endfor %}
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
         {% if orders.page == page_num %}
         <li class="page-item disabled">
           <a class="page-link" href="{{ url_for('order.order_list', page=page_num) }}">{{ page_num }}</a></li>
         </li>
         {% else %}
           <li class="page-item"><a class="page-link" href="{{ url_for('order.order_list', page=page_num) }}">{{ page_num }}</a></li>
         {% endif %}
     {% endfor %}
   </nav>


{% endblock %}

web/rest_api/templates/post_create.html
{% extends "base.html" %}
{% block content %}



<div class="container text-center mt-5" style="width:400px">
    <p>New Post</p>

    {% from "_formhelpers.html" import render_field %}

    <form method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        {{ render_field(form.staff_id)}}
        {{ render_field(form.user_id)}}
        {{ render_field(form.message)}}
        {{ render_field(form.attachment)}}
        {{form.submit()}}
    </form>

</div>

{% endblock %}

web/rest_api/templates/staff_info.html
{% extends "base.html" %}
{% block content %}



<div class="jumbotron text-center">

    {% for staff in staffs.items %}

        <h3>{{staff.name}} </h3>
        <br>
        <p>staff id:{{ staff.id }}</p>
        <p>company: {{staff.company.name}}</p>
        <p>role: {{staff.role}}</p>
        <a href="{{ url_for("staff.staff_close_account", staff_id=staff.id) }}">Delete</a> | 
        <a href="{{ url_for("staff.staff_update", staff_id=staff.id) }}">Edit</a> | 
        <br>
        <br>
    {% endfor %}
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% for page_num in staffs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
         {% if staffs.page == page_num %}
         <li class="page-item disabled">
           <a class="page-link" href="{{ url_for('staff.staff_info', page=page_num) }}">{{ page_num }}</a></li>
         </li>
         {% else %}
           <li class="page-item"><a class="page-link" href="{{ url_for('staff.staff_info', page=page_num) }}">{{ page_num }}</a></li>
         {% endif %}
     {% endfor %}
   </nav>
{% endblock %}

web/rest_api/templates/staff_register.html
{% extends "base.html" %}
{% block content %}


<div class="container text-center mt-5" style="width:400px">
    {% from "_formhelpers.html" import render_field %}

    <form method="POST">

        {{ form.hidden_tag() }}

        {{ render_field(form.username)}}
        {{ render_field(form.company_id)}}
        {{ render_field(form.role)}}
        {{ render_field(form.password)}}
        {{ render_field(form.pass_confirm)}}

        {{ form.submit() }}
    </form>

</div>




{% endblock %}

web/rest_api/templates/staff_update.html
{% extends "base.html" %}
{% block content %}



<div class="container text-center mt-5" style="width:400px">
{% from "_formhelpers.html" import render_field %}

<form method = "POST">

    {{ form.hidden_tag() }}

    username: {{staff.name}} <br>

    {{render_field(form.company_id)}}
    {{render_field(form.role)}}
    {{render_field(form.password)}}
    {{render_field(form.pass_confirm)}}

    {{ form.submit() }}
</form>
</div>



{% endblock %}

web/rest_api/templates/user_account.html
{% extends "base.html" %}
{% block content %}



<div class="jumbotron text-center">
    <h5>My Profile:</h5>
    <ul>
        <li>Username: {{ user.name }}</li>
        <li>Email: {{ user.email }}</li>
        <li>Phone: {{ user.phone }}</li>
        <li>Registration date: {{ user.date.strftime("%B %d, %Y") }}</li>
    </ul>
    <a href="{{url_for("order.order_list")}}">My Orders</a> | 
    <a href="{{url_for("user.user_update", user_id=user.id)}}">Edit Profile</a> | 
    <a href="{{url_for("user.user_close_account", user_id=user.id)}}">Close Account</a> | 


</div>


{% endblock %}

web/rest_api/templates/user_register.html
{% extends "base.html" %}
{% block content %}


<div class="container text-center mt-5" style="width:400px">
    <p>User Registration</p>

    {% from "_formhelpers.html" import render_field %}


    <form action="" method="POST">
        {{ form.hidden_tag() }}
        {{ render_field(form.username) }}
        {{ render_field(form.email)}}
        {{ render_field(form.phone)}}
        {{ render_field(form.password)}}
        {{ render_field(form.pass_confirm)}}
        {{ form.submit()}}
    </form>
</div>


{% endblock %}